### ISSUE TITLE
Data inaccuracy?

### ISSUE THREAD

**Issue by thooton** [dev-ptera/is-banano-decentralized-server#1]
https://creeper.banano.cc/network:
Official Rep - FOMO has 451m BANANO weight (~25.4%)
Banano Ratpie Rep (Genesis account) has 419m BANANO weight (~23.6%)
Official Rep - Cake has 389m BANANO weight (~21.94%)

Together making up an online voting weight of ~70.94% and putting the Nakamoto Coefficient at 1.

**Comment by dev-ptera** [comment]
This is a great question; I only included the FOMO and Cake reps as official reps because they are marked as 'official' reps on the creeper.  

If `ban_1bananobh5rat99qfgt1ptpieie5swmoth87thi74qgbfrij7dcgjiij94xr` is considered an official rep, which it probably is, I'll have to update these calculations.  I'll check with the banano team to see what they say.

**Comment by thooton** [comment]
Thanks a lot!

**Comment by dev-ptera** [comment]
You're correct; the genesis account should be counted as a 'banano-foundation' representative.  The kalium representative is not a part of the banano foundation as far as I know so I'll update this website accordingly.

**Comment by dev-ptera** [comment]
This issue is going to be fixed in another repo & hosted here: https://yellowspyglass.com/representatives

In about a month or so is-banano-decentralized.web.app will be turned off & redirected to the yellowspygass instead.

**Comment by dev-ptera** [comment]
Development for yellowspyglass is going slower than anticipated so I fixed this issue today. 

I also included Kalium as an official rep because I think they were supposed to be marked as an official rep, but creeper didn't do this.

https://is-banano-decentralized.web.app/
